language: rust
dist: xenial

matrix:
  include:
    - os: osx
      rust: stable
      env: TARGET=x86_64-apple-darwin
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
      addons:
        apt:
          packages:
            - libssl-dev
          update: true
    - os: linux
      rust: stable
      env: TARGET=i686-unknown-linux-gnu
      addons:
        apt:
          packages:
            - gcc-4.8-multilib
            - libssl-dev:i386
          update: true
    - os: linux
      rust: stable
      env: TARGET=aarch64-unknown-linux-gnu
      addons:
        apt:
          sources:
            - sourceline: 'deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports xenial main'
          packages:
            - gcc-4.8-multilib
            - gcc-4.8-aarch64-linux-gnu
            - gcc-aarch64-linux-gnu
            - libc6-arm64-cross
            - libc6-dev-arm64-cross
            - libssl1.0.0:arm64
            - zlib1g-dev:arm64
            - libssl-dev:arm64
            - zlib1g:arm64
            - zlib1g:arm64
            - libc6-dev:arm64
          update: true

before_script:
  - rustc -V
  - cargo -V
  - if [[ "${TARGET}" == "i686-unknown-linux-gnu" ]]; then rustup target add $TARGET; fi
  - |
    if [[ "${TARGET}" == "aarch64-unknown-linux-gnu" ]]; then
        rustup target add $TARGET
        aarch64-linux-gnu-gcc -v
        mkdir -p .cargo
        echo "[target.${TARGET}]" > .cargo/config
        echo "linker = \"aarch64-linux-gnu-gcc\"" >> .cargo/config
        cat .cargo/config
    fi
  - git --version
  - echo $TRAVIS_BRANCH
  - git checkout $TRAVIS_BRANCH
  - git rev-parse HEAD

script:
  - export PKG_CONFIG_ALLOW_CROSS=1
  - cargo test --verbose --features="on-ci"

notifications:
  email:
    on_success: never
    on_failure: change

before_deploy:
  - export PKG_CONFIG_ALLOW_CROSS=1
  - cargo build --target $TARGET --release
  - mkdir "git-brws-${TRAVIS_TAG}-${TARGET}"
  - cp target/$TARGET/release/git-brws LICENSE.txt README.md "git-brws-${TRAVIS_TAG}-${TARGET}"
  - zip "git-brws-${TRAVIS_TAG}-${TARGET}.zip" -r "git-brws-${TRAVIS_TAG}-${TARGET}"

deploy:
  provider: releases
  api_key:
    secure: cEHQOSxanSZC6N3D3QzK1knheL+LU63LPEXBIbwixqKvSi80u7efJw6PE7rjkMNlzt34OQrYZK2bxXcKWXhJabFCqQEfgZiPUu/1RlfW0DSVLyOsWzMJMs6cCR/x4zVvug8vrf8dYDL88zqcNaZPRwEja4VAiYJGn5muM94s7BNuBxjYny0/axEBVc8Nl2vZfCb/3L3S21Dqv6bgn37MA5zMHm5rRMLPHm7ojuOzvd7hy8H/4Jo+QzRIVPhVb5pD1/uWErAOF5NmzaEJlU3RYSsfDhb/qtqSkGvbA4p5MJpknajHk0FEliDA+h8q2y4hotLpYzP55gdRr+5+Z70yQVrRqcCc9d84akDy+hVhPJxMl5VQvm8Ks7l3pKKIZD7ywpTL2kgc5ibbiQ9Gile2dgN04SFZyGOfSIGighs2/4MT8t7jV3YyLwKCKVB13wINjWhU5647fi0j0hp+SS1RmX38pVYFyplOdCMZDLx2w6IDtT+b8TwbC3RB/dGFAT38CQiIZ5B9pAjNOkQbSKbDy2xy9u6GD5+A+8BXdZAlCxYdNXe8KaSpT+Kb46VwGnNdhi8z3LMC/JybGQ+yXlJf6e3xGdP6JqayF/qqIRUe8OOi2JgptCqEYOMKCPOYcMtK7PZAT7vRonE0mmtPeY8A72jU/Ac7lz/q9PXa50dLbgs=
  file: git-brws-${TRAVIS_TAG}-${TARGET}.zip
  skip_cleanup: true
  on:
    repo: rhysd/git-brws
    # On specific condition -> condition: $TRAVIS_RUST_VERSION = nightly
    #
    # Only deploy tagged commit
    tags: true

