name: CI
on: [push, pull_request]

jobs:
  tests:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Ensure to fetch master branch for tests
        run: git fetch origin master:master || true
      - name: Set upstream of master branch for tests
        run: git branch -u origin/master master
      - uses: dtolnay/rust-toolchain@stable
      - name: Build and run
        run: cargo run --color always -- --version
      - name: Run tests
        run: |
          cargo llvm-cov --color always --lcov --output-path lcov.info
          cargo llvm-cov --color always --no-run
        env:
          GIT_BRWS_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUST_BACKTRACE: full
          GIT_BRWS_CI_SKIP_TEST_FOR_SEARCH_API: ${{ matrix.os != 'ubuntu-latest' }}
      - uses: codecov/codecov-action@v3
        with:
          files: lcov.info

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          comopnents: rustfmt
      - run: cargo fmt -- --check --color always

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          comopnents: clippy
      - run: cargo clippy --color always --tests --benches -- -D warnings
