name: CI
on: [push, pull_request]

jobs:
  cov-linux:
    name: Coverage (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Ensure to fetch master branch for tests
        run: git fetch origin master:master || true
      - name: Set upstream of master branch for tests
        run: git branch -u origin/master master
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        env:
          GIT_BRWS_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUST_BACKTRACE: full
        with:
          args: --color always
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cobertura.xml
      # After running `cargo tarpaulin`, `cargo build` fails due to mysterious link error. Clean built things to avoid it
      - name: Clean built things
        uses: actions-rs/cargo@v1
        with:
          command: clean
      - name: Build and run
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --color always -- --version

  tests-mac-win:
    name: Tests (Mac and Windows)
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Ensure to fetch master branch for tests
        run: git fetch origin master:master || true
      - name: Set upstream of master branch for tests
        run: git branch -u origin/master master
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Run tests except for ones using search API
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --color always
        env:
          GIT_BRWS_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUST_BACKTRACE: full
          GIT_BRWS_CI_SKIP_TEST_FOR_SEARCH_API: true
      - name: Build and run
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --color always -- --version

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
          override: true
      - name: rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check --color always

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
          override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color always --tests --benches -- -D warnings
