name: CI
on: [push, pull_request]

jobs:
  unit-test:
    name: Unit tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - run: env
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Ensure to fetch master branch for tests
        run: git fetch origin master:master || true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Run tests except for ones using search API
        uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          GIT_BRWS_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUST_BACKTRACE: full
          GIT_BRWS_CI_SKIP_TEST_FOR_SEARCH_API: true
        if: matrix.os != 'ubuntu-latest'
      - name: Run all tests
        uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          GIT_BRWS_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUST_BACKTRACE: full
        if: matrix.os == 'ubuntu-latest'
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
  linters:
    name: Clippy and rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      - run: rustup component add rustfmt
      - name: rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
