name: CI
on: [push, pull_request]

jobs:
  create-release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      # upload-url: ${{ steps.TODO.outputs.TODO }}
    steps:
      - id: get_version
        # $GITHUB_REF will have a value like "refs/tags/0.3.1". Extract "0.3.1" from it
        # TODO: run: echo "::set-output name=version::${GITHUB_REF##refs/tags/}"
        run: echo "::set-output name=version::${GITHUB_REF##*/}"
      # TODO: Fail this workflow if version is empty
      # TODO: Create release and set upload-url output

  upload:
    name: Upload binary
    needs: [create-release]
    strategy:
      fail-fast: false
      matrix:
        build: [linux-64, linux-32, mac, win-64, win-32]
        include:
          - build: linux-64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - build: linux-32
            os: ubuntu-latest
            target: i686-unknown-linux-gnu
          - build: mac
            os: macos-latest
            target: x86_64-apple-darwin
          - build: win-64
            os: windows-latest
            target: x86_64-pc-windows-msvc
          - build: win-32
            os: windows-latest
            target: i686-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies on 32bit Linux
        if: matrix.build == 'linux-32'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install gcc-7-multilib lib32gcc-7-dev libssl-dev:i386
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          # TODO: Add --release
          args: --color always --target=${{ matrix.target }} --verbose
        env:
          PKG_CONFIG_ALLOW_CROSS: 1
          RUST_BACKTRACE: 1
      - id: dir
        run: echo "::set-output name=name::git-brws-${{ needs.create-release.outputs.version }}-${{ matrix.target }}"
      - name: Archive files
        if: matrix.build == 'linux-64' || matrix.build == 'linux-32' || matrix.build == 'mac'
        run: |
          mkdir ${{ steps.dir.outputs.name }}
          # TODO: Replace "/debug/" with "/release/"
          cp target/${{ matrix.target }}/debug/git-brws LICENSE.txt README.md git-brws.1 ${{ steps.dir.outputs.name }}
          zip ${{ steps.asset.outputs.path }}.zip -r ${{ steps.dir.outputs.name }}
      - name: Archive files
        if: matrix.build == 'win-64' || matrix.build == 'win-32'
        shell: bash
        run: |
          mkdir ${{ steps.dir.outputs.name }}
          # TODO: Replace "/debug/" with "/release/"
          cp target/${{ matrix.target }}/debug/git-brws.exe LICENSE.txt README.md git-brws.1 ${{ steps.dir.outputs.name }}
          7z a ${{ steps.asset.outputs.path }}.zip ${{ steps.dir.outputs.name }}
      # TODO: Upload archive
